
import { CookiesProvider } from "next-client-cookies/server"
import Navbar from "../components/Navbar/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <CookiesProvider>
          <Navbar />
          {children}
        </CookiesProvider>
      </body>

    </html >
  )
}
