
import Navbar from "../components/Navbar/Navbar";
import '../styles/reset.scss';
import "../styles/globals.scss";
import { heebo, firaMono } from "../styles/fonts";

import { getUser } from "./actions";
import AuthProvider from "../store/AuthProvider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getUser();

  return (
    <html lang="en" className={`${heebo.variable} ${firaMono.variable}`}>
      <body>
        <AuthProvider user={user}>
          <Navbar />
          {children}
        </AuthProvider>
      </body>

    </html >
  )
}
